configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-48fa80564b4addeff2643bd27446a2dca46cd0b615eeee50dd17ba96cb992305.yml
