configured_endpoints: 8
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-50c12769a17f0d41c6eb0bda802f752d0fe0fcb4ff1a7d09abe65d0764fa72cb.yml
