configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-9cc12ee4a8705bf187c9edd9b4e3c27f63639ae4da4d2436098d0d2b29f33b76.yml
