configured_endpoints: 9
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-5acd7a1b7a6bd23759fc755404fa2bc8c214c3239058ffe2808b3f1c4a3c521d.yml
