configured_endpoints: 5
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-7b61f80bc64d7a210767f0f6b8fa76d9ad392f68e73c66ce7757d28b3ba47fd7.yml
