configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/luma-ai-karanganesan%2Fluma_ai-766ca71f0cd7035d6139790f63c13ea7371436ca5e3befeaeb8a79485898c569.yml
